import Head from 'next/head';
import Link from 'next/link';
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`} />
      </Head>

      <div className="main-page">
        <div className="main-page__zaglushka">Страница пока в разарботке.<br/> Переходите сразу в каталог</div>
        <div className="main-page__buttons">
          <Link href="/catalog" className="btn main-page--main-page">Перейти в каталог</Link>
        </div>
      </div>
    </>
  )
}
